"""empty message

Revision ID: 556dc6f61112
Revises: 0d961221a303
Create Date: 2021-06-05 23:51:39.824928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556dc6f61112'
down_revision = '0d961221a303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
